---
version: '3.2'

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - intranet
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./init.sh:/docker-entrypoint-initdb.d/init.sh"

  adminer:
    image: adminer
    networks:
      - intranet
    restart: always
    ports:
      - 8080:8080

  keto-migrate:
    depends_on:
      - postgres
    image: oryd/keto:v0.8.0-alpha.2
    networks:
      - intranet
    command: migrate up -y -c /etc/config/keto.yml
    environment:
      - DSN=postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: .
        target: /etc

  keto:
    image: oryd/keto:v0.8.0-alpha.2
    container_name: keto
    networks:
      - intranet
    depends_on:
      - keto-migrate
    ports:
      - '4466:4466'
      - '4467:4467'
    environment:
      - DSN=postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    command: serve -c /etc/config/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /etc

#  keto-init:
#    image: oryd/keto:v0.7.0-alpha.1-sqlite
#    environment:
#      - KETO_WRITE_REMOTE=keto:4467
#    volumes:
#      - type: bind
#        source: .
#        target: /home/ory
#    command: relation-tuple create /home/ory/relation-tuples
#    restart: on-failure

networks:
  intranet: {}