version: "3.2"

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./init.sh:/docker-entrypoint-initdb.d/init.sh"

  keto-migrate:
    depends_on:
      - postgres
    image: oryd/keto:v0.8.0-alpha.2
    #    networks:
    #      - intranet
    command: migrate up -y -c /etc/config/keto3.yml
    environment:
      - DSN=postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: .
        target: /etc

  keto:
    image: oryd/keto:v0.8.0-alpha.2
    depends_on:
      - keto-migrate
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /etc/config/keto3.yml
    environment:
      - DSN=postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /etc

  keto-init:
    image: oryd/keto:v0.8.0-alpha.2
    environment:
      - KETO_WRITE_REMOTE=keto:4467
    volumes:
      - type: bind
        source: .
        target: /etc
    command: relation-tuple create /etc/config/relation-tuples
    restart: on-failure
