version: v0.8.0-alpha.2

log:
  format: json
  leak_sensitive_values: false
  level: debug

serve:
  read:
    host: localhost
    port: 4466
  write:
    host: localhost
    port: 4467

#dsn: memory
dsn: postgres://keto:keto@localhost:5432/keto
