version: v0.7.0-alpha.1

log:
  level: debug

namespaces:
  - id: 0
    name: videos

dsn: postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467