version: v0.8.0-alpha.2

log:
  format: json
  leak_sensitive_values: false
  level: debug

namespaces:
  - id: 0
    name: videos
  - id: 1
    name: OnePass:account

serve:
  read:
    host: localhost
    port: 4466
  write:
    host: localhost
    port: 4467

#dsn: memory
dsn: postgres://keto:keto@postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
